class AllMethod{
public static void main(String[] args)
{
	System.out.println("Running main in all method....");
        Mobile.makeCall();
        Mobile.sendMessage();
        Mobile.browseInternet();
        Mobile.takePhoto();
        Mobile.recordVideo();
        Mobile.playMusic();
        Mobile.setAlarm();
        Mobile.openCalendar();
        Mobile.checkBatteryPercentage();
        Mobile.turnOnFlashlight();
        Mobile.turnOffFlashlight();
        Mobile.lockScreen();
        Mobile.unlockScreen();
        Mobile.connectWifi();
		Mobile.takeScreenshot();
		Mobile.sendPhoto();
		Mobile.uploadPhoto();
		Mobile.recievePhoto();
	    Mobile.addContact();
	    Mobile.deleteContact();
	    Mobile.enableLocation();
		
		System.out.println("\n");
		
		Mechanic.changeOil();
        Mechanic.replaceSparkPlugs();
        Mechanic.checkBatteryVoltage();
        Mechanic.adjustBrakePads();
        Mechanic.rotateTires();
        Mechanic.inspectSuspension();
        Mechanic.cleanFuelInjectors();
        Mechanic.testIgnitionCoil();
        Mechanic.flushCoolantSystem();
        Mechanic.replaceAirFilter();
        Mechanic.diagnoseEngineTrouble();  
        Mechanic.alignWheelAlignment();
        Mechanic.testAlternatorOutput();
        Mechanic.replaceDriveBelt();
        Mechanic.adjustClutchPedal();
        Mechanic.lubricateChassis();
        Mechanic.inspectExhaustSystem();
        Mechanic.testFuelPressure();
        Mechanic.replaceOxygenSensor();
        Mechanic.checkTransmissionFluid();
        Mechanic.inspectSteeringComponents();
        Mechanic.rechargeACSystem();
        Mechanic.cleanThrottleBody();
		
		System.out.println("\n");
		
		Person.eat();
        Person.sleep();
        Person.walk();
        Person.run();
        Person.talk();
        Person.listen();
        Person.read();
        Person.write();
        Person.think();
        Person.study();
        Person.work();
        Person.exercise();
        Person.meditate();
        Person.cook();
        Person.clean();
        Person.drive();
        Person.swim();
        Person.dance();
        Person.sing();
        Person.play();
        Person.laugh();
        Person.cry();
        Person.smile();
		
		System.out.println("\n");
		
		WashingMachine.start();
		WashingMachine.stop();
		WashingMachine.setProgram();
		WashingMachine.setTemperature();
		WashingMachine.setSpinSpeed();
		WashingMachine.addDetergent();
		WashingMachine.addFabricSoftener();
		WashingMachine.addClothes();
		WashingMachine.removeClothes();
		WashingMachine.pause();
		WashingMachine.resume();
		WashingMachine.setDelay();
		WashingMachine.setRinseCycle();
		WashingMachine.setQuickWash();
		WashingMachine.setHeavyDuty();
		WashingMachine.setNormalWash();
		WashingMachine.setDelicateWash();
		WashingMachine.setSilentMode();
		WashingMachine.getRemainingTime();
		WashingMachine.getProgram();
		WashingMachine.getTemperature();
		WashingMachine.getSpinSpeed();
		
		System.out.println("\n");
		
		Barber.greetCustomer();
        Barber.cutHair();
        Barber.styleHair();
        Barber.shampooHair();
        Barber.trimBeard();
        Barber.shaveBeard();
        Barber.giveFacial();
        Barber.applyHairColor();
        Barber.doHighlights();
        Barber.doPerming();
        Barber.doBraiding();
        Barber.doUpdo();
        Barber.doScalpMassage();
        Barber.doHotTowelTreatment();
        Barber.doHairExtensions();
        Barber.doHairStraightening();
        Barber.doHairCurling();
        Barber.doHairBleaching();
        Barber.doHairThreading();
        Barber.doHairWaxing();
        Barber.doHairRelaxing();
        Barber.recommendHairProducts();
		
    }
}
